baseURL: /
languageCode: en-us
title: DRTUNICORN

disableKinds: [taxonomy,taxonomyTerm]
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  author: drtunicorn
  description: Minimalist bloat-free website.

menu:
  main:
    - name: home
      url: "/"
      weight: 1

    - name: about
      url: "/about"
      weight: 2

    - name: ~drtunicorn
      url: "https://github.com/drtunicorn"
      weight: 3
