name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Jakarta"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'

      - name: Create source
        run: |
          mkdir -p ./static/sources
          tar czvf ./static/sources/drtunicorn.tar.gz archetypes content layouts static config.yml LICENSE README

      - uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DRTUNICORN }}
          publish_dir: ./public
          publish_branch: gh-pages
